# Generated by Django 3.2.18 on 2023-04-22 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
