# Generated by Django 3.2.18 on 2023-04-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(max_length=220),
        ),
    ]
