# Generated by Django 3.2.18 on 2023-03-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_times',
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_times', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_showtimes', to='movie_booking.movie')),
            ],
            options={
                'unique_together': {('movie', 'show_date', 'show_times')},
            },
        ),
    ]
