# Generated by Django 3.2.18 on 2023-04-23 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0002_alter_reservation_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='show_times',
            new_name='show_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='showings',
            field=models.ManyToManyField(related_name='movies', to='movie_booking.Showtime'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_booking.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('movie', 'show_date', 'show_time')},
        ),
    ]
